name: Presidential Innovation Fellows Foundation

#URL of site, include http://, do not include a trailing slash
url: http://presidentialinnovation.org
# url: http://localhost:4000

#files to exclude, array
exclude:
  - README.md
  - Rakefile
  - "/vendor/bundle"
  - Gemfile
  - Gemfile.lock
  - CNAME

#posts per page
paginate: 5
paginate_path: "/updates/page:num/"

#number of items in RSS feed
rss_limit: 20

#permalink structure, see https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /updates/:year/:month/:day/:title/

#whether production or dev, minifies JS, bool
production: true

#build config

kramdown:
  parse_block_html: true

timezone: America/New_York
encoding: UTF-8
safe: true

markdown: kramdown
timezone: America/New_York
encoding: UTF-8

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"


sass:
  sass_dir: _sass
  style: :compressed
  images_dir: 'img/content'
  javascripts_dir: 'assets/js'

gems:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
